/*-
 * Copyright (C) 2002, 2017, Oracle and/or its affiliates. All rights reserved.
 *
 * This file was distributed by Oracle as part of a version of Oracle Berkeley
 * DB Java Edition made available at:
 *
 * http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html
 *
 * Please see the LICENSE file included in the top-level directory of the
 * appropriate version of Oracle Berkeley DB Java Edition for a copy of the
 * license and additional information.
 */

package com.sleepycat.je.rep.stream;

import com.sleepycat.je.utilint.StatDefinition;
import com.sleepycat.je.utilint.StatDefinition.StatType;

/**
 * Per-stat Metadata for HA Feeder Transaction statistics.
 */
public class FeederTxnStatDefinition {

    public static final String GROUP_NAME = "FeederTxns";
    public static final String GROUP_DESC = "FeederTxns statistics";

    public static StatDefinition TXNS_ACKED =
        new StatDefinition("txnsAcked", "Number of Transaction ack'd.");

    public static StatDefinition TXNS_NOT_ACKED =
        new StatDefinition("txnsNotAcked",
                           "Number of Transactions not Ack'd.");

    public static StatDefinition TOTAL_TXN_MS =
            new StatDefinition("totalTxnMS",
                               "The total elapsed MS across all txns from " +
                               "transaction start to end.");

    public static StatDefinition ACK_WAIT_MS =
        new StatDefinition("ackWaitMS", "Total MS waited for acks.");

    public static StatDefinition LAST_COMMIT_VLSN =
        new StatDefinition("lastCommitVLSN",
                           "The VLSN of the last committed transaction on" +
                           " the master, or 0 if not known or this node is" +
                           " not the master.",
                           StatType.CUMULATIVE);

    public static StatDefinition LAST_COMMIT_TIMESTAMP =
        new StatDefinition("lastCommitTimestamp",
                           "The commit timestamp of the last committed" +
                           " transaction on the master, or 0 if not known" +
                           " or this node is not the master.",
                           StatType.CUMULATIVE);

    public static StatDefinition VLSN_RATE =
        new StatDefinition("vlsnRate",
                           "A moving average of the rate replication data is" +
                           " being generated by the master, in VLSNs per" +
                           " minute, or 0 if not known or this node is not" +
                           " the master.");
}
